
export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum IncidentStatus {
  NEW = 'NEW',
  INVESTIGATING = 'INVESTIGATING',
  CONTAINED = 'CONTAINED',
  CLOSED = 'CLOSED'
}

export enum View {
  DASHBOARD = 'DASHBOARD',
  FEED = 'FEED',
  ANALYSIS = 'ANALYSIS',
  INGESTION = 'INGESTION',
  DETECTION = 'DETECTION',
  INCIDENTS = 'INCIDENTS',
  CASES = 'CASES',
  ACTORS = 'ACTORS',
  AUDIT = 'AUDIT',
  VULNERABILITIES = 'VULNERABILITIES',
  MITRE = 'MITRE',
  OSINT = 'OSINT',
  EVIDENCE = 'EVIDENCE',
  SYSTEM = 'SYSTEM',
  REPORTS = 'REPORTS',
  CAMPAIGNS = 'CAMPAIGNS',
  SUPPLY_CHAIN = 'SUPPLY_CHAIN',
  SIMULATION = 'SIMULATION',
  ORCHESTRATOR = 'ORCHESTRATOR',
  VIP_PROTECTION = 'VIP_PROTECTION',
  MESSAGING = 'MESSAGING',
  SETTINGS = 'SETTINGS',
  THEME = 'THEME'
}

export interface ChartDataPoint {
    name: string;
    value: number;
}
